# Generated by Django 3.1.7 on 2021-03-21 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganspace_viewer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewer',
            name='seed',
            field=models.IntegerField(default='000000000'),
        ),
    ]
