# Generated by Django 3.1.7 on 2021-03-22 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganspace_viewer', '0003_auto_20210322_1251'),
    ]

    operations = [
        migrations.CreateModel(
            name='model_properties',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.CharField(max_length=50)),
                ('component_values', models.FilePathField()),
                ('seed', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='ganspace_model',
            name='number_of_componenets',
        ),
        migrations.RemoveField(
            model_name='ganspace_model',
            name='seed',
        ),
        migrations.AddField(
            model_name='ganspace_model',
            name='hide_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ganspace_model',
            name='number_of_components',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ganspace_model',
            name='className',
            field=models.CharField(max_length=50),
        ),
    ]
