# Generated by Django 3.1.7 on 2021-03-22 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganspace_viewer', '0004_auto_20210322_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ganspace_model',
            name='number_of_components',
            field=models.IntegerField(default=70),
        ),
        migrations.AlterField(
            model_name='model_properties',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganspace_viewer.ganspace_model'),
        ),
    ]
