# Generated by Django 3.1.7 on 2021-03-22 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ganspace_viewer', '0002_viewer_seed'),
    ]

    operations = [
        migrations.CreateModel(
            name='ganspace_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField()),
                ('seed', models.IntegerField(default='0000000')),
                ('number_of_componenets', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Viewer',
        ),
    ]
