# Generated by Django 3.1.7 on 2021-03-22 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ganspace_viewer', '0006_remove_model_properties_classname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model_properties',
            name='component_values',
        ),
        migrations.AddField(
            model_name='model_properties',
            name='className',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ganspace_viewer.ganspace_model'),
        ),
    ]
